### ISSUE TITLE
When log out password is saved

### ISSUE THREAD

**Issue by HelgaMond** [tango-controls/tango-webapp#85]
When log out the password is saved.

![logout_passsaved](https://user-images.githubusercontent.com/27626862/36530517-52ec24b0-17cc-11e8-8b09-18f51e734344.png)

**Comment by Ingvord** [comment]
Well, this is actually a feature not a bug. When browser has user credentials it fills in the form. This mechanism is also used for single sign on feature.

**Comment by Ingvord** [comment]
Seems that this is really confusing for users. These fields must be cleaned out after logoff
